config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/cart'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/charges', to: 'charges#new'
  post '/charges', to: 'charges#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @cart = Cart.all
    # Amount in cents
    @total = 0
    @cart.each do |cart|
      @total = @total + (cart.product.price * cart.quantity.to_i)
    end


  items = "Tea"

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => (@total * 100).to_i,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    PurchaseMailer.purchase_confirmation(items, @total).deliver_now
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def cart
    @cart = Cart.all

    @total = 0
    @cart.each do |cart|
      @total = @total + (cart.product.price * cart.quantity.to_i)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= @total %></strong>!</h2>

app/views/charges/new.html.erb
<h1>Welcome to Tracy's Tea Shop</H1>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="total">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Tracy's Tea"
          data-description="100grams of Licorice Tea ($5.00)"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyBags</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/cart.html.erb
<h1>Cart:</h1>
<table>
    <thead>
    <tr>
      <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <% @cart.each do |cart| %>
        <tr>
            <td><%= cart.product.title %></td>
            <td><%= cart.product.price %></td>
            <td><%= cart.quantity %></td>
        </tr>
    <% end %>
        <tr>
            <td>Total: </td>
            <td><%= @total %></td>
            <td><%= @cart.sum(:quantity) %></td>
        </tr>
</tbody>
</table>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="total">
      <span>Amount: <%= @total %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Tracy's Tea"
          data-description="100grams of Licorice Tea ($5.00)"
          data-amount="<%= (@total * 100).to_i%>"
          data-locale="auto"></script>
<% end %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>